@uri = http://localhost:8000/api
@logoutUri = http://localhost:8000/auth/google

### 
GET {{ uri }}/posts
Content-Type: application/json
Accept: application/json

###
POST {{ uri }}/posts
Content-Type: application/json
Accept: application/json

{
    "name" : "Post 1",
    "desc" : "Testing post, testing 1234"
}

###
POST {{ uri }}/posts
Content-Type: application/json
Accept: application/json

{
    "name" : "Post 2",
    "desc" : "Testing post number 2, testing 1234"
}

###
get {{ uri }}/posts/2
Content-Type: application/json
Accept: application/json


###
PUT {{ uri }}/posts/3
Content-Type: application/json
Accept: application/json

{
    "name" : "",
    "desc" : "Testing post number 2, Then saying testing 1234"
}


###
DELETE {{ uri }}/posts/2
Content-Type: application/json
Accept: application/json


### Test posts endpoint
GET {{ uri }}/posts
Authorization: Bearer 87|IrrTBgNMi2mdysksPVypj2A3QT4Ob5t9XNWL7NP4a32e32c8
Accept: application/json


### Test logout endpoint
POST {{ uri }}/auth/google/logout 
Authorization: Bearer 77|VGUQjJHcohtFqyCiRaPQiSIR7tGGRc593ufn03Vs796cc01f
Accept: application/json