@uri = http://localhost/api
@logoutUri = http://localhost:8000/auth/google
@accessKey = 20|tWZdd0DLCzOdIgMyowDtmkEGQmhXbOkaKlHLUHc19cd7aa5c

### 
GET {{ uri }}/posts
Content-Type: application/json
Accept: application/json

###
POST {{ uri }}/posts
Content-Type: application/json
Accept: application/json

{
    "name" : "Post 1",
    "desc" : "Testing post, testing 1234"
}

###
POST {{ uri }}/posts
Content-Type: application/json
Accept: application/json

{
    "name" : "Post 2",
    "desc" : "Testing post number 2, testing 1234"
}

###
get {{ uri }}/posts/2
Content-Type: application/json
Accept: application/json


###
PUT {{ uri }}/posts/3
Content-Type: application/json
Accept: application/json

{
    "name" : "",
    "desc" : "Testing post number 2, Then saying testing 1234"
}


###
DELETE {{ uri }}/posts/2
Content-Type: application/json
Accept: application/json


### Test posts endpoint
GET {{ uri }}/posts
Authorization: Bearer 87|IrrTBgNMi2mdysksPVypj2A3QT4Ob5t9XNWL7NP4a32e32c8
Accept: application/json


### Test logout endpoint
POST {{ uri }}/auth/google/logout 
Authorization: Bearer 77|VGUQjJHcohtFqyCiRaPQiSIR7tGGRc593ufn03Vs796cc01f
Accept: application/json

### Test new yt_url creation
POST {{ uri }}/yt-urls
Authorization: Bearer 137|3tiXVKNPnx0hUL6o0aGy9Df4isHv6RnjRgqAgNPwf95c077e
Content-Type: application/json
Accept: application/json

{
    "yt_url" : "https://www.youtube.com/watch?v=ozkg_iW9mNU"
}

### Test getting that url 
GET  {{ uri }}/yt-urls
Authorization: Bearer {{accessKey}}
Content-Type: application/json
Accept: application/json

### Test getting that specific url 
GET  {{ uri }}/yt-urls/2
Authorization: Bearer {{accessKey}}
Content-Type: application/json
Accept: application/json


### Test new yt_url update
PUT {{ uri }}/yt-urls/1
Authorization: Bearer 139|ST96Ut5BExVjVljpPUff5ewjvBipiCMiNgnbvmxS3e710c7c
Content-Type: application/json
Accept: application/json

{
    "yt_url" : "https://youtu.be/YA2Lxfw4SSw?list=TLGGABOYhUzoLlkwOTAyMjAyNQ"
}

### Test creating content body
POST {{uri}}/contents
Authorization: Bearer {{accessKey}}
Content-Type: application/json
Accept: application/json

{
    "title" : "title9",
    "body" : "body9"
}


### Test getting all content
GET {{uri}}/contents
Authorization: Bearer {{accessKey}}
Content-Type: application/json
Accept: application/json


### Test getting a specific content
GET {{uri}}/contents/1
Content-Type: application/json
Accept: application/json


### Test content update
PUT {{uri}}/contents/1
Authorization: Bearer {{accessKey}}
Content-Type: application/json
Accept: application/json

{
    "title" : "This is the updated title",
    "body" : "This is the updated body"
}


### Test fetching all page contents (index)
GET {{uri}}/page-contents
Authorization: Bearer {{accessKey}}
Content-Type: application/json
Accept: application/json


### Test fetching a specific page content (show)
GET {{uri}}/page-contents/test-paths
Authorization: Bearer {{accessKey}}
Content-Type: application/json
Accept: application/json


### Test creating a new page content (store)
POST {{uri}}/page-contents
Authorization: Bearer {{accessKey}}
Content-Type: application/json
Accept: application/json

{
    "path": "/test-paths",
    "content": {
        "layout": "single",
        "contents": {
            "content1": "This is a test page content"
        }
    }
}


### Test updating the page content (update)
PUT {{uri}}/page-contents/test-path
Authorization: Bearer {{accessKey}}
Content-Type: application/json
Accept: application/json

{
    "content": {
        "layout": "gallary",
        "contents": {
            "content1": "Updated test content",
            "galleryItems": [
                {"image": "data:image/jpeg;base64,...", "caption": "Test image"}
            ]
        }
    }
}

### Test error case: duplicate path (store)
POST {{uri}}/page-contents
Authorization: Bearer {{accessKey}}
Content-Type: application/json
Accept: application/json

{
    "path": "/test-path",
    "content": {
        "layout": "single",
        "contents": {"content1": "Duplicate test"}
    }
}

### Test deleting the page content (destroy)
DELETE {{uri}}/page-contents/test-paths
Authorization: Bearer {{accessKey}}
Content-Type: application/json
Accept: application/json