@uri = http://localhost/api
@logoutUri = http://localhost:8000/auth/google
@accessKey = 2|5wxR1YVpU15lAt2JI4bYXV4wXjZufGSHdnuOQQb8a583bfcb

### 
GET {{ uri }}/posts
Content-Type: application/json
Accept: application/json

###
POST {{ uri }}/posts
Content-Type: application/json
Accept: application/json

{
    "name" : "Post 1",
    "desc" : "Testing post, testing 1234"
}

###
POST {{ uri }}/posts
Content-Type: application/json
Accept: application/json

{
    "name" : "Post 2",
    "desc" : "Testing post number 2, testing 1234"
}

###
get {{ uri }}/posts/2
Content-Type: application/json
Accept: application/json


###
PUT {{ uri }}/posts/3
Content-Type: application/json
Accept: application/json

{
    "name" : "",
    "desc" : "Testing post number 2, Then saying testing 1234"
}


###
DELETE {{ uri }}/posts/2
Content-Type: application/json
Accept: application/json


### Test posts endpoint
GET {{ uri }}/posts
Authorization: Bearer 87|IrrTBgNMi2mdysksPVypj2A3QT4Ob5t9XNWL7NP4a32e32c8
Accept: application/json


### Test logout endpoint
POST {{ uri }}/auth/google/logout 
Authorization: Bearer 77|VGUQjJHcohtFqyCiRaPQiSIR7tGGRc593ufn03Vs796cc01f
Accept: application/json

### Test new yt_url creation
POST {{ uri }}/yt-urls
Authorization: Bearer 137|3tiXVKNPnx0hUL6o0aGy9Df4isHv6RnjRgqAgNPwf95c077e
Content-Type: application/json
Accept: application/json

{
    "yt_url" : "https://www.youtube.com/watch?v=ozkg_iW9mNU"
}

### Test getting that url 
GET  {{ uri }}/yt-urls
Authorization: Bearer {{accessKey}}
Content-Type: application/json
Accept: application/json

### Test getting that specific url 
GET  {{ uri }}/yt-urls/2
Authorization: Bearer {{accessKey}}
Content-Type: application/json
Accept: application/json


### Test new yt_url update
PUT {{ uri }}/yt-urls/1
Authorization: Bearer 139|ST96Ut5BExVjVljpPUff5ewjvBipiCMiNgnbvmxS3e710c7c
Content-Type: application/json
Accept: application/json

{
    "yt_url" : "https://youtu.be/YA2Lxfw4SSw?list=TLGGABOYhUzoLlkwOTAyMjAyNQ"
}

### Test creating content body
POST {{uri}}/contents
Authorization: Bearer {{accessKey}}
Content-Type: application/json
Accept: application/json

{
    "title" : "title9",
    "body" : "body9"
}


### Test getting all content
GET {{uri}}/contents
Authorization: Bearer {{accessKey}}
Content-Type: application/json
Accept: application/json


### Test getting a specific content
GET {{uri}}/contents/1
Content-Type: application/json
Accept: application/json


### Test content update
PUT {{uri}}/contents/1
Authorization: Bearer {{accessKey}}
Content-Type: application/json
Accept: application/json

{
    "title" : "This is the updated title",
    "body" : "This is the updated body"
}